version: '3.0'

services:
  panel:
    image: ghcr.io/redstonewizard08/pterodocker/panel:main
    ports:
      - 8086:80
    environment:
      - DB_USER=pterodactyl
      - DB_PASSWORD=pterodactyl
    volumes:
      - ./sql:/var/lib/mysql
      - ./panel:/var/www/pterodactyl
  wings:
    image: ghcr.io/redstonewizard08/pterodocker/wings:main
    depends_on:
      - panel
    volumes:
      - ./docker:/var/lib/docker
      - ./config:/etc/pterodactyl
    ports:
      - 2028:2028
      - 8088:8088