version: '3.0'

services:
  panel:
    image: ghcr.io/pedstonewizard08/pterodocker/panel
    ports:
      - 8086:80
    environment:
      - DB_USER=pterodactyl
      - DB_PASSWORD=pterodactyl
    volumes:
      - ./sql:/var/lib/mysql
  wings:
    image: ghcr.io/pedstonewizard08/pterodocker/wings
    depends_on:
      - panel
    volumes:
      - ./docker:/var/lib/docker
      - ./config:/etc/pterodactyl
    ports:
      - 2028:2028
      - 8088:8088